# Related contents configuration
includeNewer = true
threshold = 60
toLower = false

[[indices]]
name = "tags"
weight = 100

[[indices]]
name = "cuisines"
weight = 150

[[indices]]
name = "categories"
weight = 200